version: '3'

services:
  rebuz_node:
    build: .
    image: rebuz_node:latest
    container_name: rebuz_node
    hostname: node
    domainname: rebuz.no
    environment:
      - NODE_PUBLIC_HOST=rebuz.no
      - MONGO_DB_HOST=rebuz_mongo
    ports:
      - 80:3000
    networks:
      rebuz:

  rebuz_mongo:
    image: mongo:latest
    container_name: rebuz_mongo
    hostname: mongo
    domainname: rebuz.no
    ports:
      - 27017:27017
    networks:
      rebuz:

networks:
  rebuz:
